### ISSUE TITLE
JS errors in RTE due to some localization issues

### ISSUE THREAD

**Issue by andreasfernandez** [7elix/TYPO3.CMS.Styleguide#22]
Applying commit 3e037a298d98286d48943b9e8f9612d1ad60fb2a breaks "RTE 1" with the following JavaScript errors:
>Uncaught TypeError: Cannot read property 'editElement' of undefined
>Uncaught TypeError: Cannot read property 'ShowMicrodata-Tooltip' of undefined
>Uncaught TypeError: Cannot read property 'Technische Universitat Ilmenau' of undefined
>Uncaught TypeError: Cannot read property 'Insert custom element' of undefined
>Uncaught TypeError: Cannot read property 'fontsize' of undefined
>Uncaught TypeError: Cannot read property 'mozilla_smile' of undefined
>Uncaught TypeError: Cannot read property 'Technische Universitat Ilmenau' of undefined
>Uncaught TypeError: Cannot read property 'PasteToggleTooltip' of undefined
>Uncaught TypeError: Cannot read property 'Quick Tag Editor' of undefined

**Comment by lolli42** [comment]
RTE 1 always loads for me, I'm unable to reproduced ... could you nail this a bit further?

**Comment by benjaminkott** [comment]
![image](https://cloud.githubusercontent.com/assets/3243119/7670471/3743c748-fca6-11e4-9f33-620eef157225.png)

**Comment by lolli42** [comment]
Still unable to reproduce. Could you help me? Did you select some different BE language or did you localize the record?

**Comment by andreasfernandez** [comment]
I'm on de the default backend language and no website languages are present, so there is no translation.

**Comment by lolli42** [comment]
i think this is resolved now.
