### ISSUE TITLE
404 after clicking "form engine test" in TCA records

### ISSUE THREAD

**Issue by tmotyl** [7elix/TYPO3.CMS.Styleguide#33]
Not Found

The requested URL /typo3/alt_doc.php was not found on this server.
there is a hardcoded path to alt_doc in styleguide/Resources/Private/Templates/Styleguide/Tca.html

**Comment by wouter90** [comment]
Solved with https://github.com/7elix/TYPO3.CMS.Styleguide/commit/454b834e64aac5c48e8e539141c516c312460e1c
