### ISSUE TITLE
Error in compare databases

### ISSUE THREAD

**Issue by tmotyl** [7elix/TYPO3.CMS.Styleguide#63]
recent change from https://github.com/7elix/TYPO3.CMS.Styleguide/commit/88b28fc9d7d9c626035294cfc9c6af0f26ccd729

is causing install tool compare databases to throw errrors no mysql. 
Also acceptance tests are failing now.

**Comment by lolli42** [comment]
I can't find an issue here anymore with current core master. Can you still reproduce, Tymek?

**Comment by tmotyl** [comment]
still have it.
Compare databases shows following updates:

```
 ALTER TABLE tx_styleguide_elements_basic CHANGE deleted `deleted` SMALLINT DEFAULT 0 NOT NULL 
Current value: deleted TINYINT(1) DEFAULT '0' NOT NULL
 ALTER TABLE tx_styleguide_elements_basic CHANGE hidden `hidden` SMALLINT DEFAULT 0 NOT NULL 
Current value: hidden TINYINT(1) DEFAULT '0' NOT NULL
 ALTER TABLE tx_styleguide_elements_basic CHANGE t3ver_state `t3ver_state` SMALLINT DEFAULT 0 NOT NULL 
Current value: t3ver_state TINYINT(1) DEFAULT '0' NOT NULL
 ALTER TABLE tx_styleguide_elements_basic CHANGE input_36 `input_36` DATE DEFAULT NULL 
Current value: input_36 DATE DEFAULT '0000-00-00' NOT NULL
 ALTER TABLE tx_styleguide_elements_basic CHANGE input_37 `input_37` DATETIME DEFAULT NULL 
Current value: input_37 DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL
```
and when I try to execute it, it throws an error:
```
Error: Invalid default value for 'input_36'
Error: Invalid default value for 'input_37'
```

**Comment by lolli42** [comment]
So, that's a strict mode thing.
Could you give me sql_mode from mysql and/or setDBinit typo3 settings? i'm still running mysql 5.5 locally ;)

**Comment by wouter90** [comment]
Your database is already wrong at this point and I'm not sure if we can fix this. Morton merged https://github.com/7elix/TYPO3.CMS.Styleguide/commit/88b28fc9d7d9c626035294cfc9c6af0f26ccd729 to fix this in ext:styleguide

**Comment by tmotyl** [comment]
I'll try  to drop styleguide columns and recreate them

**Comment by tmotyl** [comment]
after dropping tables and recreating works now, I'm closing the issue.
