### ISSUE TITLE
DB Error - Incorrect integer value: '' for column 'l18n_parent' 

### ISSUE THREAD

**Issue by MonaMuzaffar** [7elix/TYPO3.CMS.Styleguide#81]
exec_UPDATEquery
array(4 items)
   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_UPDATEquery' (60 chars)
   ERROR => 'Incorrect integer value: '' for column 'l18n_parent' at row 1' (61 chars)
   lastBuiltQuery => 'UPDATE tx_styleguide_elements_rsainput_inline_1_child SET pid='86',parentid=
      '4',parenttable='tx_styleguide_elements_rsainput',uid='4',sys_language_uid='
      0',l18n_parent='',l18n_diffsource='lipsum',hidden='0',rsainput_1='lipsum' WH
      ERE uid = 4' (239 chars)
   debug_backtrace => 'require(typo3/sysext/backend/Resources/Private/Php/backend.php),typo3/index.
      php#3 // {closure}#25 // TYPO3\CMS\Backend\Http\Application->run#24 // TYPO3
      \CMS\Core\Core\Bootstrap->handleRequest#93 // TYPO3\CMS\Backend\Http\Backend
      ModuleRequestHandler->handleRequest#310 // TYPO3\CMS\Backend\Http\BackendMod
      uleRequestHandler->dispatchModule#88 // TYPO3\CMS\Extbase\Core\Bootstrap->ru
      n#182 // TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#193 // TYPO3\CMS\Ex
      tbase\Mvc\Web\BackendRequestHandler->handleRequest#206 // TYPO3\CMS\Extbase\
      Mvc\Dispatcher->dispatch#32 // TYPO3\CMS\Extbase\Mvc\Controller\ActionContro
      ller->processRequest#86 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController
      ->callActionMethod#175 // call_user_func_array#282 // TYPO3\CMS\Styleguide\C
      ontroller\StyleguideController->tcaCreateAction# // TYPO3\CMS\Styleguide\Tca
      DataGenerator\Generator->create#139 // TYPO3\CMS\Styleguide\TcaDataGenerator
      \TableHandler\General->handle#122 // TYPO3\CMS\Styleguide\TcaDataGenerator\R
      ecordData->generate#61 // TYPO3\CMS\Styleguide\TcaDataGenerator\FieldGenerat
      or\TypeInline1n->generate#52 // TYPO3\CMS\Core\Database\DatabaseConnection->
      exec_UPDATEquery#81 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#267' (1216 chars)

**Comment by tmotyl** [comment]
same problem here, for a moment had to apply a dirty hack:
```
diff --git a/Classes/TcaDataGenerator/RecordData.php b/Classes/TcaDataGenerator/RecordData.php
index f9163df..7e2d514 100644
--- a/Classes/TcaDataGenerator/RecordData.php
+++ b/Classes/TcaDataGenerator/RecordData.php
@@ -47,8 +47,13 @@ class RecordData
                 'fieldValues' => $fieldValues,
             ];
             try {
-                $generator = $resolver->resolve($data);
-                $fieldValues[$fieldName] = $generator->generate($data);
+                if (in_array($fieldName, ['l18n_parent', 'l10n_parent']))
+                {
+                    $fieldValues[$fieldName] = 0;
+                } else {
+                    $generator = $resolver->resolve($data);
+                    $fieldValues[$fieldName] = $generator->generate($data);
+                }
             } catch (GeneratorNotFoundException $e) {
                 // No op if no matching generator was found
             }
```

**Comment by lolli42** [comment]
fixed with https://github.com/7elix/TYPO3.CMS.Styleguide/pull/82
